# Generated by Django 5.0 on 2026-01-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/%Y/%m/', verbose_name='Изображение')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='Название (EN)')),
                ('title_uz', models.CharField(blank=True, max_length=200, verbose_name='Название (UZ)')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (UZ)')),
                ('category', models.CharField(choices=[('woven', 'Вшивные этикетки'), ('printed', 'Печатные этикетки'), ('hang_tags', 'Навесные бирки'), ('stickers', 'Стикеры'), ('packaging', 'Упаковка')], max_length=100, verbose_name='Категория')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Элемент портфолио',
                'verbose_name_plural': 'Портфолио',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['order'], name='content_por_order_cede3b_idx'), models.Index(fields=['category'], name='content_por_categor_71e539_idx'), models.Index(fields=['is_published'], name='content_por_is_publ_df0abe_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Основное изображение')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL slug')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Название (EN)')),
                ('name_uz', models.CharField(blank=True, max_length=200, verbose_name='Название (UZ)')),
                ('short_description_ru', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание (RU)')),
                ('short_description_en', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание (EN)')),
                ('short_description_uz', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание (UZ)')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_en', models.TextField(blank=True, verbose_name='Описание (EN)')),
                ('description_uz', models.TextField(blank=True, verbose_name='Описание (UZ)')),
                ('category', models.CharField(choices=[('woven_labels', 'Вшивные этикетки'), ('printed_labels', 'Печатные этикетки'), ('hang_tags', 'Навесные бирки'), ('stickers', 'Стикеры'), ('packaging', 'Упаковка')], max_length=100, verbose_name='Категория')),
                ('features', models.JSONField(blank=True, default=dict, help_text='Формат: {"ru": ["пункт 1", "пункт 2"], "en": [...], "uz": [...]}', verbose_name='Характеристики')),
                ('order', models.IntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_featured', models.BooleanField(default=False, help_text='Показывать на главной странице', verbose_name='Избранное')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукция',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['slug'], name='content_pro_slug_8e955f_idx'), models.Index(fields=['category'], name='content_pro_categor_e72276_idx'), models.Index(fields=['is_published'], name='content_pro_is_publ_15c07f_idx'), models.Index(fields=['is_featured'], name='content_pro_is_feat_610179_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/%Y/%m/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображения продукта',
                'ordering': ['order', 'id'],
            },
        ),
    ]
