# Generated by Django 5.0 on 2026-01-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('form_submit', 'Form Submission'), ('form_start', 'Form Started'), ('file_upload', 'File Upload'), ('button_click', 'Button Click'), ('link_click', 'Link Click')], db_index=True, max_length=50, verbose_name='Тип события')),
                ('page', models.CharField(max_length=500, verbose_name='Страница')),
                ('language', models.CharField(db_index=True, max_length=10, verbose_name='Язык')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='Реферер')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('session_id', models.CharField(db_index=True, max_length=100, verbose_name='Session ID')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Дополнительные данные события', verbose_name='Метаданные')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Событие аналитики',
                'verbose_name_plural': 'События аналитики',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='analytics_a_timesta_b8f215_idx'), models.Index(fields=['event_type', '-timestamp'], name='analytics_a_event_t_c6fe80_idx'), models.Index(fields=['session_id', '-timestamp'], name='analytics_a_session_720940_idx')],
            },
        ),
    ]
