# Generated by Django 5.0 on 2026-01-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('product_type', models.CharField(choices=[('woven', 'Вшивные этикетки'), ('printed', 'Печатные этикетки'), ('hang_tags', 'Навесные бирки'), ('stickers', 'Стикеры'), ('other', 'Другое')], max_length=100, verbose_name='Тип продукта')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Количество')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('file', models.FileField(blank=True, null=True, upload_to='leads/%Y/%m/', verbose_name='Файл')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('contacted', 'Связались'), ('qualified', 'Квалифицирован'), ('closed', 'Закрыт'), ('rejected', 'Отклонен')], default='new', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(blank=True, help_text='Откуда пришла заявка', max_length=100, verbose_name='Источник')),
                ('language', models.CharField(default='ru', max_length=10, verbose_name='Язык')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='leads_lead_created_921505_idx'), models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'), models.Index(fields=['product_type'], name='leads_lead_product_211d3b_idx')],
            },
        ),
    ]
